"""add location to volunteer

Revision ID: 7553fd147ecf
Revises: 8b5b9b0fa3d2
Create Date: 2025-07-27 10:36:49.131027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7553fd147ecf'
down_revision = '8b5b9b0fa3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('location')

    # ### end Alembic commands ###
